import test from 'node:test';import assert from 'node:assert/strict';import os from 'node:os';import path from 'node:path';import fs from 'node:fs';
process.env.DB_PATH=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'product-test-')),'test.sqlite');
const {default:handler,validate}=await import('../api/records.js');const {config,catalog}=await import('../public/data.js');
function input(){return catalog.length?{itemId:catalog[0].id,quantity:1,details:config.id==='pricepal'?{basket:JSON.stringify({rice:2}),store:'market'}:{}}:{custom:true,title:'Example transaction',price:5000,quantity:1,details:config.id==='shoppadi'?{type:'sale',cost:'2000'}:{}};}
async function call(method,body,cookie,origin){let headers={};let result;const req={method,headers:{host:'localhost','content-type':'application/json',...(cookie?{cookie}:{}),...(origin?{origin}:{})},body};const res={setHeader(k,v){headers[k]=v},end(raw){result=JSON.parse(raw)}};await handler(req,res);return {status:res.statusCode,body:result,cookie:headers['Set-Cookie']?.split(';')[0]};}
test('valid record and server-authoritative totals',()=>{const r=validate({...input(),price:1});assert.ok(r.id);assert.ok(r.total>=0);if(catalog.length&&config.id!=='pricepal')assert.equal(r.price,catalog[0].price);if(config.id==='pricepal')assert.equal(r.total,4800)});
test('rejects invalid quantity and missing catalog item',()=>{assert.throws(()=>validate({...input(),quantity:-1}));assert.throws(()=>validate({...input(),quantity:1.2}));assert.throws(()=>validate({itemId:'missing',quantity:1}));});
test('persistence, private session isolation, origin validation and transitions',async()=>{const initial=await call('GET');assert.equal(initial.status,200);const created=await call('POST',input(),initial.cookie);assert.equal(created.status,201);const reload=await call('GET',null,initial.cookie);assert.equal(reload.body.records.length,1);const other=await call('GET');assert.equal(other.body.records.length,0);assert.equal((await call('POST',input(),initial.cookie,'https://evil.example')).status,403);const invalid=await call('PATCH',{id:created.body.record.id,status:'Invented'},initial.cookie);assert.equal(invalid.status,409);const status=config.transitions[created.body.record.status]?.[0];if(status){const changed=await call('PATCH',{id:created.body.record.id,status},initial.cookie);assert.equal(changed.status,200);assert.equal(changed.body.record.status,status)}assert.equal((await call('PATCH',{id:created.body.record.id,status},other.cookie)).status,404);});
test('malformed session gets a fresh workspace',async()=>{assert.equal((await call('GET',null,'session=abc.invalid')).status,200)});
